tables:
  mailqueue_queue:
    field:
      id:
        primary_key: true
        type: varchar(50)
        not_null: true
      send_id:
        type: varchar(50)
      subject:
        type: varchar(255)
      body:
        type: mediumtext
      rank:
        type: int(13)
      mail_from:
        type: varchar(255)
      mail_to:
        type: varchar(255)
      date_from:
        type: datetime
      date_to:
        type: datetime
      error_text:
        type: mediumtext
      account_id:
        type: varchar(50)
        foreing_key:
          reference_table: account
          reference_field: id
          on_delete: CASCADE
          on_update: CASCADE
      tag:
        description: Optional field. Could be used to check if a reciever already got a specific message.
        type: varchar(255)
  mailqueue_file:
    field:
      id:
        description: This is also filename in Mailqueue folder.
        primary_key: true
        type: varchar(50)
        not_null: true
      name:
        description: Example file.pdf
        type: varchar(255)
      encoding:
        description: Default is base64.
        type: varchar(50)
        default: base64
      type:
        description: Example application/pdf
        type: varchar(50)
      disposition:
        description: Default is attachment.
        type: varchar(50)
        default: attachment
  mailqueue_attachment:
    field:
      id:
        primary_key: true
        type: varchar(50)
        not_null: true
      queue_id:
        primary_key: true
        type: varchar(50)
        not_null: true
        foreing_key:
          reference_table: mailqueue_queue
          reference_field: id
          on_delete: CASCADE
          on_update: CASCADE
      file_id:
        primary_key: true
        type: varchar(50)
        not_null: true
        foreing_key:
          reference_table: mailqueue_file
          reference_field: id
          on_delete: CASCADE
          on_update: CASCADE
  mailqueue_send:
    field:
      id:
        primary_key: true
        type: varchar(50)
        not_null: true
      ip:
        type: varchar(50)
extra:
  _description: Extra field to add to each table if not exist in schema.
  field:
    created_at:
      type: timestamp
      default: CURRENT_TIMESTAMP
    updated_at:
      type: timestamp
    created_by:
      type: varchar(50)
    updated_by:
      type: varchar(50)
      
        
        
        
        